import React from 'react';
import { type Data } from 'plotly.js';
import Plot from 'react-plotly.js';

interface ChartViewerProps {
    chartData: { data: Data[]; layout: Record<string, unknown> };
    onClose: () => void;
    className?: string;
}

export const ChartViewer: React.FC<ChartViewerProps> = ({ chartData, onClose, className = "" }) => {
    if (!chartData) return null;

    return (
        <div className={`bg-white rounded-2xl shadow-sm border border-zinc-200 overflow-hidden flex flex-col h-full ${className}`}>
            <div className="p-4 border-b border-zinc-100 flex items-center justify-between bg-zinc-50/50">
                <div className="flex items-center gap-2">
                    <div className="w-8 h-8 rounded-lg bg-indigo-100 flex items-center justify-center text-indigo-700">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="16" x2="12" y2="12"></line><line x1="12" y1="8" x2="12.01" y2="8"></line></svg>
                    </div>
                    <div>
                        <h2 className="text-sm font-semibold text-zinc-900">Visualization</h2>
                        <p className="text-xs text-zinc-500">Generated by DataMind AI</p>
                    </div>
                </div>
                <button
                    onClick={onClose}
                    className="w-8 h-8 rounded-lg hover:bg-zinc-100 border border-transparent hover:border-zinc-200 flex items-center justify-center text-zinc-400 hover:text-zinc-600 transition-all"
                    title="Close Chart"
                >
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
                </button>
            </div>

            <div className="flex-1 overflow-hidden p-2 bg-white relative">
                <Plot
                    data={chartData.data}
                    layout={{
                        ...chartData.layout,
                        autosize: true,
                        width: undefined,
                        height: undefined,
                        margin: { l: 50, r: 20, b: 50, t: 20 },
                        font: { family: 'Inter, sans-serif' },
                        paper_bgcolor: 'rgba(0,0,0,0)',
                        plot_bgcolor: 'rgba(0,0,0,0)',
                    }}
                    useResizeHandler={true}
                    style={{ width: '100%', height: '100%' }}
                    config={{ responsive: true, displayModeBar: true, displaylogo: false }}
                />
            </div>
        </div>
    );
};
